# Generated by Django 5.1.2 on 2024-10-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bln_active',
        ),
    ]
